### PR TITLE
Import and Parse FHIT Configuration

### PR DESCRIPTION
**Pull request by jafeltra**
This PR defines the FHIT configuration and implements importing a configuration file. The process is fairly similar to the SUSHI configuration import process, but if there are places anyone notices to improve on that, let me know in the review.

The basic configuration file defines what FHIR packages you want to compare. You include the package using any key (aka alias) you want to use throughout the configuration file and specify the FHIR package id and version. For example:

```yaml
packages:
  uscore:
    id: hl7.fhir.us.core
    version: 5.0.1
```
The `uscore` alias can then be used to reference that package when defining the alignments.

The configuration file also defines how to specify those alignments. Within an array of alignments, each alignment is an object with the alias of the package as a key and the profile id/name as the value. For example:

```yaml
alignments:
  - uscore: USCorePatientProfile
    mcode: CancerPatient
```

Some use cases that are important to note:

- If an alignment wants to compare one profile to a core FHIR resource, you should include that FHIR version in the `packages` configuration and refer to it as usual within the `alignment` and include the name of the package resource. For example:
  ```yaml
    packages:
      fhirR4:
        id: hl7.fhir.r4.core
        version: 4.0.1
      # and uscore and mcode...

    alignments:
      - uscore: USCorePatientProfile
        fhirR4: Patient
  ```
- If an alignment doesn't have a profile or core resource to compare to the other package, that means it would automatically be INFEASIBLE in the comparison table. To specify this in the configuration, you should include the package you're comparing to and specify `NONE` instead of any profile/resource. There isn't much to specify in the import side of this, but it is a good note to be aware of. For example:
  ```yaml
  alignments:
    - uscore: USCorePatientProfile
      mcode: NONE
  ```

For now, `packages` and `alignments` are the only parts of the configuration file and they are both required. In the future, we may add more optional or required fields to the configuration.

Right now, this branch only implements the `ensureConfiguration` and `importConfiguration` but does not call them from anywhere. The tests show many of the cases to be aware of, but if you want to try this locally, the simple function below can be used to import a `fhit-config.yaml` file and parse the configuration:

```typescript
import { readFileSync } from 'fs-extra';
import { ensureConfiguration, importConfiguration } from './import';

function simpleTest() {
  const configPath = ensureConfiguration('<path to a folder with a fhit-config.yaml file>');
  if (!configPath) {
    throw new Error('no config');
  }

  const configYaml = readFileSync(configPath, 'utf8');
  const config = importConfiguration(configYaml, 'fhit-config.yaml');
  console.log(config);
}

simpleTest();

```

I also changed a few other things while implementing the import. I update the ESLint file to use the rules that align with the version of ESLint we're using. I also added in the `withLocation` formatter in the Logger.

### CODE REVIEW

**Comment by cmoesel** [comment]
When I try to run the tests, they're failing w/ this error:
```
 FAIL  test/import/importConfiguration.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/cmoesel/dev/standardhealth/fhir-matches/node_modules/yaml/dist/compose/composer.js:41
            if (prelude[i + 1]?.[0] !== '#') i += 1;
                               ^

    SyntaxError: Unexpected token '.'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/yaml/dist/index.js:3:16)
```
Did you see this @jafeltra?

Also, I'm just now noticing that this repo is not setup to run tests in a GH action.  Oops.

**Comment by jafeltra** [comment]
>Did you see this @jafeltra?
>
>Also, I'm just now noticing that this repo is not setup to run tests in a GH action. Oops.

I feel like I did see this at one point, but I don't see it now. I'll look into it and see if I can figure out what triggers it and how to prevent it.

Also, how would we feel if I maybe snuck in a GH actions file?

**Comment by cmoesel** [comment]
@jafeltra - I just tried this using Node 14 instead of Node 12 and it worked.  I think Node 12 is EOL (or near EOL) now, so I'm comfortable requiring at least Node 14.  So... nevermind!

Also, I definitely would not be mad if you snuck in a GH actions file!

**Review by cmoesel — CHANGES_REQUESTED** [review]
This is very nicely done, @jafeltra.  It's very robust and comprehensive and the error messages are clearly and helpful.

I did find two cases that I think should result in logged errors but currently fly through undetected:

1. If an alignment only has one entry:
    ```
    alignments:
      - usc: us-core-patient
      - usc: us-core-condition-encounter-diagnosis
        ips: Condition
    ```
2. If an alignment has > 2 entries:
    ```
    alignments:
      - usc: us-core-patient
        ips: Patient-uv-ips
        fhir4: Patient
    ```

I think these should log an error and skip that alignment.

Other than that, it all looks great!

**Comment by jafeltra** [comment]
Thanks for the comments @cmoesel! A quick summary of the changes I made:

- [471a73f](https://github.com/standardhealth/fhir-matches/pull/8/commits/471a73ffb53e146b381454b7f8a0d7c2ad2b0325) logs an error in the two cases you pointed out, and it also fixes the two inline suggestions you made to simplify the `Object.entries` functions.
- [e0020b2](https://github.com/standardhealth/fhir-matches/pull/8/commits/e0020b2cd8cc96c4af3b23a9e0516e8e36a10952) adds a test that uses the `withLocation` formatter that I added in to the logger.
- I did sneak in a GH actions file in [0a1ee32](https://github.com/standardhealth/fhir-matches/pull/8/commits/0a1ee32df629c413e6aa7b21b811942aecf2a4b4) but then the tests promptly broke because we were making actual requests to download packages through FPL. So I mocked out those functions in the two test suites that made actual network calls in [f2ae41a](https://github.com/standardhealth/fhir-matches/pull/8/commits/f2ae41a03d3b74a2da4b08b2f50b7c1216f06818).

I was also going to add a note into the README to require Node 14 or later, but we already had that in there! So I didn't making any changes there.

I think this is set to be re-reviewed now!

**Review by cmoesel — APPROVED** [review]
This looks great, Julia! Well done!

**Review by julianxcarter — APPROVED** [review]
Tested this out by running the provided test script against the simple config included in our test fixtures. This looks good to me!

**Pull request merged**
